Refactor script to rename Git stashes

diff --git a/shell/bin/rename_stash b/shell/bin/rename_stash
--- a/shell/bin/rename_stash
+++ b/shell/bin/rename_stash
@@ -5,33 +5,58 @@
 #   $1: The index of the stash to rename
 #   $2: The new name for the stash
 
-set -eu
- 
-local stash_index="$1"
-local new_stash_name="$2"
-local stashes_total=$($(git stash list | wc -l) - 1)
+set -euf
 
+declare stash_index=${1:-}
+declare new_stash_name=${2:-}
+declare stashes_total
+declare stash_info
+declare new_commit_hash
+declare tree
+declare parents
+
+stashes_total=$(($(git stash list | wc -l) - 1))
+
+# Validate user input
 if [[ -z "$stash_index" ]] || [[ -z "$new_stash_name" ]]; then
   echo "Invalid input: Both the stash index and a new stash name are required."
-  return 1  
-elif [[ "$stash_index" -gt "$stashes_total" ]] || [[ "$stash_index" -lt 0 ]]; then
+  exit 1
+elif [[ $stash_index =~ [^0-9]+ ]]; then
+  echo "Invalid input: Specifed index is not a number."
+  exit 1
+elif [[ "$stashes_total" -le 1 ]]; then
+  echo "Invalid Input: No stashes found."
+  exit 1
+elif [[ "$stash_index" -gt "$stashes_total" ]] ||
+  [[ "$stash_index" -lt 0 ]]; then
   echo "Invalid input: No stash with the specifed index exists."
-  return 1
+  exit 1
 fi
 
-local stash_info=($(git show --no-patch --pretty=format:"%T %P" stash@{$stash_index} | sed -e 's/ / -p /g'))
+stash_info="$(
+  git show \
+    --no-patch \
+    --pretty=format:"%T %P" \
+    "stash@{$stash_index}" |
+    sed -e 's/ / -p /g'
+)"
+
+tree=$(cut -d ' ' -f 1 <<< "$stash_info")
+parents=$(cut -d ' ' -f 2- <<< "$stash_info")
 
 # Get the commit for our new stash
-local new_commit_hash=$(git commit-tree "${stash_info[@]}" -m "$new_stash_name")
+# ('$parents' is intentionally not quoted to allow expansion on whitespace)
+new_commit_hash="$(git commit-tree $parents -m "$new_stash_name" "$tree")"
 
 # Drop the old stash
-git stash drop --quiet stash@{$stash_index} 
+git stash drop --quiet "stash@{$stash_index}"
 
 # Create a new one in its place
 git stash store \
-  -m "$(git show -s --format=%B $new_commit_hash)" \
+  -m "$(git show -s --format=%B "$new_commit_hash")" \
   --quiet \
-  $new_commit_hash
+  "$new_commit_hash"
 
-echo "Renamed stash@{$stash_index} as '$new_stash_name'"
+echo "Renamed stash@{$stash_index} to '$new_stash_name'"
+
 exit 0
